language: cpp
os:
  - osx
  - linux
sudo: required
dist: trusty
compiler:
  - clang
  - gcc
env:
  - GMOCK_VER=1.8.0
  - GMOCK_VER=1.7.0
  - GMOCK_PATH=/usr/src/gmock #1.6.0 from ubuntu trusty repo
matrix:
  exclude:
    - os: osx
      env: GMOCK_PATH=/usr/src/gmock
    - os: osx
      compiler: gcc #does anyone on osx use it?
  include:
    - os: linux
      compiler: gcc
      env: GMOCK_VER=1.8.0 VALGRIND_TESTS=ON

before_script:
  - git clone https://github.com/cgreen-devs/cgreen.git
  - git -C cgreen checkout 7030597
  - cmake -E make_directory cgreen/build
  - cmake -E chdir cgreen/build cmake -G Ninja -DCMAKE_INSTALL_PREFIX=${HOME}/usr ..
  - cmake --build cgreen/build
  - cmake --build cgreen/build --target install
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo ldconfig; fi

addons:
  apt:
    packages:
      - libboost-thread-dev
      - libboost-system-dev
      - libboost-regex-dev
      - libboost-date-time-dev
      - libboost-filesystem-dev
      - libboost-program-options-dev
      - libboost-test-dev
      - google-mock
      - ninja-build
      - valgrind

before_install:
  - if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then brew update && brew install ninja; fi

script: ./travis.sh

# default notifications: https://docs.travis-ci.com/user/notifications#Notifications
