language: cpp
os:
  - osx
  - linux
sudo: required
dist: trusty
compiler:
  - clang
  - gcc
env:
  - GMOCK_VER=1.8.0
  - GMOCK_VER=1.7.0
  - GMOCK_PATH=/usr/src/gmock #1.6.0 from ubuntu trusty repo
matrix:
  exclude:
    - os: osx
      env: GMOCK_PATH=/usr/src/gmock
    - os: osx
      compiler: gcc #does anyone on osx use it?

before_script:
  - git clone https://github.com/cgreen-devs/cgreen.git
  - mkdir cgreen/build && pushd cgreen/build && cmake .. && make && sudo make install && popd

addons:
  apt:
    packages:
      - libboost-thread-dev
      - libboost-system-dev
      - libboost-regex-dev
      - libboost-date-time-dev
      - libboost-program-options-dev
      - libboost-test-dev
      - google-mock

script: ./travis.sh

notifications:
  email:
    - cukes-devs@googlegroups.com

branches:
  only:
    - master
    - travis-experimentation
